### PR TITLE
fix: scroll service fixes

### PR DESCRIPTION
**Pull request by alihassan143**

### CODE REVIEW

**Comment by alihassan143** [comment]
@LucasXu0

**Comment by LucasXu0** [comment]
@alihassan143 any related issues?

**Comment by alihassan143** [comment]
@LucasXu0  scroll service did not scroll automatically when users start writing now its working perfectly on mobile and desktop

**Comment by alihassan143** [comment]
@LucasXu0  why there is more horizontal padding even you add padding in editor style

**Comment by alihassan143** [comment]
@LucasXu0  image builder shows error when alignment is not provided converting from html to node now that bug fixes

**Comment by LucasXu0** [comment]
Hey, @alihassan143. Would you mind submitting the PR to the appflowy-editor repo after this PR merged? https://github.com/AppFlowy-IO/appflowy-editor/pull/129. Because this repo doesn't include any CI checks.

**Comment by LucasXu0** [comment]
And please refrain from adding the override function such as `insertContent` since we are currently using Flutter 3.7.x.

**Comment by alihassan143** [comment]
@LucasXu0  actually i am using latest flutter version that why this added 
ok i will do that

**Pull request closed without merging**
